version: "3.9"
services:
  ocr:
    tty: true
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development